### ISSUE TITLE
欢迎在这里提问！

### ISSUE THREAD

**Issue by nubot-nudt** [nubot-nudt/simatch#1]
欢迎大家在这里提问或者提出一些建议和意见。  
步骤如下：  
1. 新建一个issue；  
2. 附上详细的说明。

**Comment by yinxiangcsu** [comment]
[nubot_control.txt](https://github.com/nubot-nudt/simatch/files/465489/nubot_control.txt)
测试的例子有一点问题

**Comment by nubot-nudt** [comment]
在我的测试里面是没有问题的。在射门之前，机器人需要带上球，带上球的标准是与足球足够的近以及与球的角度误差足够的小，这两个参数在[sim_config](https://github.com/nubot-nudt/simatch/blob/master/src/gazebo_visual/nubot_gazebo/config/global_config.yaml)里面有，就是dribble_distance_thres和dribble_angle_thres。所以，建议在调用射门服务之前先判断机器人是否带上了足球，这样才能保证射门成功。

**Comment by 979938197** [comment]
新修改的源码，在进行catkin_make ，执行cmake时 simatch/src/realtime_tools/CMakeLists.txt报错，请问还需要配置哪些东西
