### ISSUE TITLE
在Ubuntu18.10上编译报错的问题

### ISSUE THREAD

**Issue by MissYourSmile** [nubot-nudt/simatch#13]
我使用的是Ubuntu18.10的系统，此系统版本下无法安装ROS Kinetic版本，按照ROS官方文档的说法：
> ROS Kinetic ONLY supports Wily (Ubuntu 15.10), Xenial (Ubuntu 16.04) and Jessie (Debian 8) for debian packages.

在Ubuntu18.10下，使用了ROS Melodic，在编译clone下来的源码时出现了一些错误，主要集中为以下几种情况：
1. 引用 boost 库 thread.hpp 时报错，此错误在其他 ROS 工程中不会重现。
```sh
/usr/include/boost/date_time/gregorian_calendar.ipp:78:55: error: ambiguous overload for ‘operator-’ (operand types are ‘int’ and ‘const boost::gregorian::greg_month’)
     unsigned short a = static_cast<unsigned short>((14-ymd.month)/12);
```
2. 最终指向 Angle.hpp 中的运算符重载的错误
```sh
/home/dhd/c-workspace/simatch/src/robot_code/nubot_common/include/Angle.hpp:132:44: note: candidate: nubot::Angle nubot::operator-(const nubot::Angle&, const _Tp&) [with _Tp = boost::gregorian::greg_month]
 template<typename _Tp> static inline Angle operator - (const Angle & a , const _Tp & b){
```
3. 大批量因找不到 math 类引起的错误
```sh
In file included from /home/dhd/c-workspace/simatch/src/gazebo_visual/nubot_gazebo/src/nubot_gazebo.cc:9:0:
/home/dhd/c-workspace/simatch/src/gazebo_visual/nubot_gazebo/src/nubot_gazebo.hh:55:8: error: ‘math’ does not name a type; did you mean ‘tanh’?
        math::Vector3    position;
```
请问是否可以在不改动大量代码的前提下完成运行平台的升级，

**Comment by emingeming** [comment]
我遇到同样的问题。 已经都解决了。
问题1是boost包库兼容性问题，最新版也存在。解决方案： 修改boost库包。
问题2是变量声明方式与原版本不同。解决方案：要修改变量声明。
问题3是math类以及相关类的Gazebo9.0的重新定义，与Gazebo之前版本不同。解决方案：修改函数接口。

我将修改后的代码在Ubuntu18.04+Gazebo9.0上测试过了.申请了Pull request, 等批准通过就能看到了.

**Comment by MissYourSmile** [comment]
> 我遇到同样的问题。 已经都解决了。
> 问题1是boost包库兼容性问题，最新版也存在。解决方案： 修改boost库包。
> 问题2是变量声明方式与原版本不同。解决方案：要修改变量声明。
> 问题3是math类以及相关类的Gazebo9.0的重新定义，与Gazebo之前版本不同。解决方案：修改函数接口。
> 
> 我将修改后的代码在Ubuntu18.04+Gazebo9.0上测试过了.申请了Pull request, 等批准通过就能看到了.

您好，我尝试修改boost库相关的报错，错误主要是时间日期库里边的year、mouth等和int类型运算导致的。
我已尝试：在报错点直接加上强制类型转换是有效的，但总觉得这不是一劳永逸的方式，然后我尝试修改`boost::gregorian::greg_month`的内容，试图增加`operator int` 重载来解决问题，但是此处已经有了`operator unsigned short`重载，加上int重载便会引入新的错误。
请问您修改boost库的思路是什么呢？

**Comment by zhouzhiqian** [comment]
@emingeming 很高兴你的加入，前面由于在忙别的事情，没注意到你的pull request我会尽快整合，然后发布melodic的版本，欢迎测试

**Comment by zhouzhiqian** [comment]
@MissYourSmile@emingeming重新分析了这个问题，根源在于angle这个类里面，进行了一些不合理的运算符的重载，因此，我删除了四个没必要的运算符重载（他们与boost里面的内容发生了冲突），同时将其他的运算符撤销了static的定义（这个操作也是没有必要的，尤其是对于内联函数的定义，并不需要声明static）

**Comment by zhouzhiqian** [comment]
@emingeming @MissYourSmile 重新分析了这个问题，根源在于angle这个类里面，进行了一些不合理的运算符的重载，因此，我删除了四个没必要的运算符重载（他们与boost里面的内容发生了冲突），同时将其他的运算符撤销了static的定义（这个操作也是没有必要的，尤其是对于内联函数的定义，并不需要声明static）
