### ISSUE TITLE
 fatal error: nubot_hwcontroller/DebugInfo.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by euuiuyt** [nubot-nudt/simatch#18]
运行catkin_make时报错

 fatal error: nubot_hwcontroller/DebugInfo.h: 没有那个文件或目录
 #include "nubot_hwcontroller/DebugInfo.h"
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by nubot-nudt** [comment]
注释掉这句话，重新编译一次即可
