### ISSUE TITLE
在编译的时候出现了文件中的问题

### ISSUE THREAD

**Issue by zjy0912yyds** [nubot-nudt/simatch#19]
[lssues.docx](https://github.com/nubot-nudt/simatch/files/7271493/lssues.docx)

**Comment by zhouzhiqian** [comment]
看起来像是版本的问题，确认一下gazebo的版本，ros的版本，目前已经测试过的是18.04+melodic+gazebo9 （gazebo9相较于gazebo 7 （kinectic使用）的改动还是挺大的）
