### ISSUE TITLE
gazebo5 error

### ISSUE THREAD

**Issue by RogerYong** [nubot-nudt/simatch#4]
system info:

ubuntu 14.04.5 desktop i386
ros jade
gazebo5

error info:

run  simatch with one computer

`$ source devel/setup.bash`
`$ roslaunch nubot_gazebo game_ready.launch`

![1](https://cloud.githubusercontent.com/assets/12882512/19218269/f1b1b6c6-8e27-11e6-8d88-6d64677840ce.png)
![2](https://cloud.githubusercontent.com/assets/12882512/19218283/1576b58e-8e28-11e6-97d5-6314ac8fc4ed.png)

**Comment by nubot-nudt** [comment]
Please try to configure your operation environment as stated in the README.md. And also try to compile the package without any errors.
