### ISSUE TITLE
how  can I add  a camera to the nubot?

### ISSUE THREAD

**Issue by HubFire** [nubot-nudt/simatch#7]
I wang to add a camera to the nubot ,but I cant't  find the  urdf file which define the robot

**Comment by nubot-nudt** [comment]
Currently only sdf file is available. You could edit the sdf file to add the camera.

**Comment by HubFire** [comment]
OK，I will try .  Thank you for your guidance on my robot learning way !

**Comment by nubot-nudt** [comment]
You are welcome!
